/**
 * Per-town driving facts from Strokestown — generated by
 * scripts/generate-town-data.mjs (Routes API). Regenerate if the fee rules in
 * functions/index.js TRAVEL_CONFIG change. Intros/villages are hand-written.
 */
export type TownData = {
  slug: string;
  name: string;
  county: string;
  lat: number;
  lng: number;
  drivingKm: number;
  drivingMin: number;
  /** € call-out fee (0 in the free zone or out of area) */
  calloutFee: number;
  /** Within the 45 km driving cutoff — bookable online */
  inServiceArea: boolean;
  freeZone: boolean;
  nearbyVillages: string[];
  intro: string;
};

export const towns: TownData[] = [
  {
    slug: "strokestown",
    name: "Strokestown",
    county: "Co. Roscommon",
    lat: 53.7767,
    lng: -8.0983,
    drivingKm: 0,
    drivingMin: 0,
    calloutFee: 0,
    inServiceArea: true,
    freeZone: true,
    nearbyVillages: ["Tulsk","Elphin","Scramoge","Kilglass","Ruskey"],
    intro:
      "Strokestown is home base — Jake's Car Care operates from the town itself, so there's never a call-out fee here. Whether you're near the Park House end of town or out toward Kilglass, Strokestown bookings can often be fitted in around other jobs at short notice.",
  },
  {
    slug: "roscommon-town",
    name: "Roscommon Town",
    county: "Co. Roscommon",
    lat: 53.6333,
    lng: -8.1897,
    drivingKm: 19.7,
    drivingMin: 18,
    calloutFee: 5,
    inServiceArea: true,
    freeZone: false,
    nearbyVillages: ["Four Mile House","Ballymurray","Knockcroghery","Kilteevan"],
    intro:
      "Roscommon Town is Jake's busiest patch outside home — a straightforward run down the N61 most weekends. Estate driveways, workplace car parks near the town centre: wherever the car is parked, the van comes to it.",
  },
  {
    slug: "castlerea",
    name: "Castlerea",
    county: "Co. Roscommon",
    lat: 53.7681,
    lng: -8.4922,
    drivingKm: 30.1,
    drivingMin: 28,
    calloutFee: 10,
    inServiceArea: true,
    freeZone: false,
    nearbyVillages: ["Ballintubber","Ballymoe","Loughglynn","Frenchpark"],
    intro:
      "Castlerea sits about half an hour west of Strokestown, and Jake covers it — and the villages along the way — most weekends. Handy if you use the train: leave the car at home on Saturday morning and come back to it valeted.",
  },
  {
    slug: "boyle",
    name: "Boyle",
    county: "Co. Roscommon",
    lat: 53.9714,
    lng: -8.2958,
    drivingKm: 30.9,
    drivingMin: 32,
    calloutFee: 10,
    inServiceArea: true,
    freeZone: false,
    nearbyVillages: ["Cootehall","Knockvicar","Croghan","Ballyfarnon"],
    intro:
      "Boyle marks the northern edge of the regular run. Between Lough Key day trips and daily commuting, north Roscommon cars earn their grime — a weekend valet on your own driveway beats queueing at a wash bay in town.",
  },
  {
    slug: "carrick-on-shannon",
    name: "Carrick-on-Shannon",
    county: "Co. Leitrim",
    lat: 53.9469,
    lng: -8.09,
    drivingKm: 25.8,
    drivingMin: 28,
    calloutFee: 10,
    inServiceArea: true,
    freeZone: false,
    nearbyVillages: ["Leitrim Village","Drumsna","Jamestown","Cortober"],
    intro:
      "Apartment blocks and marina car parks don't make car care easy in Carrick-on-Shannon — which is exactly where a mobile valet earns its keep. Jake works right where you park; all he needs is access to an outdoor tap and a socket.",
  },
  {
    slug: "ballymahon",
    name: "Ballymahon",
    county: "Co. Longford",
    lat: 53.5647,
    lng: -7.7656,
    drivingKm: 35.5,
    drivingMin: 31,
    calloutFee: 15,
    inServiceArea: true,
    freeZone: false,
    nearbyVillages: ["Tang","Abbeyshrule","Colehill","Kenagh"],
    intro:
      "Ballymahon and the Center Parcs corridor make an easy southern run. South Longford customers usually book the car in for a weekend morning — the valet happens on the driveway while you get on with your Saturday.",
  },
  {
    slug: "edgeworthstown",
    name: "Edgeworthstown",
    county: "Co. Longford",
    lat: 53.6957,
    lng: -7.6089,
    drivingKm: 38.5,
    drivingMin: 32,
    calloutFee: 15,
    inServiceArea: true,
    freeZone: false,
    nearbyVillages: ["Ardagh","Ballinalee","Abbeylara","Granard"],
    intro:
      "Edgeworthstown's spot on the N4 and N55 means serious commuter mileage — and the road film that comes with it. Jake covers the town and the surrounding townlands at weekends, working on your own driveway or outside the office.",
  },
  {
    slug: "longford-town",
    name: "Longford Town",
    county: "Co. Longford",
    lat: 53.7276,
    lng: -7.7933,
    drivingKm: 23.4,
    drivingMin: 22,
    calloutFee: 10,
    inServiceArea: true,
    freeZone: false,
    nearbyVillages: ["Newtownforbes","Killashee","Clondra","Drumlish"],
    intro:
      "Longford Town is closer than most people guess — about 25 minutes from Strokestown door to door. Estates around the town, offices on the Dublin Road, apartments near the station: Jake valets wherever you can park, and the exact call-out fee appears the moment you enter your Eircode.",
  },
  {
    slug: "athlone",
    name: "Athlone",
    county: "Co. Westmeath",
    lat: 53.4239,
    lng: -7.9407,
    drivingKm: 50.7,
    drivingMin: 46,
    calloutFee: 0,
    inServiceArea: false,
    freeZone: false,
    nearbyVillages: ["Glasson","Ballykeeran","Monksland","Bealnamulla"],
    intro:
      "Athlone falls just outside the standard 45 km booking area, so online slots aren't offered — but for bigger jobs (a full valet, or two or three cars together) Jake will make the trip by arrangement.",
  },
  {
    slug: "loughrea",
    name: "Loughrea",
    county: "Co. Galway",
    lat: 53.1986,
    lng: -8.5686,
    drivingKm: 102,
    drivingMin: 79,
    calloutFee: 0,
    inServiceArea: false,
    freeZone: false,
    nearbyVillages: ["Craughwell","Kilrickle","Bullaun"],
    intro:
      "Loughrea is well beyond the everyday run from Strokestown, but for full-day work — multiple cars, a small fleet, or a serious detail — Jake will travel by arrangement. Message ahead with what you need and he'll quote the trip.",
  },
];

export const inAreaTowns = towns.filter((t) => t.inServiceArea);
export const byArrangementTowns = towns.filter((t) => !t.inServiceArea);
